schema_version = "1.0.0"

id = "o_oo_math_controller"

version = "0.4.8"

name = "Math Controller"

tagline = "Add math group node that acts according to written formulas"

maintainer = "o_oo_Gote510"

type = "add-on"

website = "https://github.com/o-oo-gote510/Math-Controller-Addon.git"


blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = ["2026 o_oo_gote510"]

tags = ["Node"]

 [build]
paths_exclude_pattern = [
    "/.git*",
    "/*.zip",
    "/images/",
]
